export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED'

export const RESET_CART = 'RESET_CART'